database:
  host: localhost
  port: 3306
  user: root
  password: root
  database: minecraft
  table: you_long_relation
friend:
  #传功配置
  upgrade:
    #命令全是以控制台方式执行
    commands:
      - 'tell XiaoFanQwQ friend命令执行1'
      - 'tell XiaoFanQwQ friend命令执行2'
    #允许等级差
    level: 2
    #传功时间 单位秒
    time: 300



lover:
  #双修配置
  upgrade:
    #传功时间
    time: 3600
    commands:
      - 'tell XiaoFanQwQ lover命令执行1'
      - 'tell XiaoFanQwQ lover命令执行2'




master:
  count: 3
  upgrade:
    commands:
      master:
        - 'tell XiaoFanQwQ master命令执行1'
        - 'tell XiaoFanQwQ master命令执行2'‘
      disciple:
        - 'tell XiaoFanQwQ disciple命令执行1'
        - 'tell XiaoFanQwQ disciple命令执行2'‘
    # 传功时间
    time: 3600




